services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - '8080:8080'
        volumes:
            - .:/app
            - ~/.gradle:/root/.gradle
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mydatabase
            - SPRING_DATASOURCE_USERNAME=myuser
            - SPRING_DATASOURCE_PASSWORD=mypassword
        command: ['java', '-jar', 'build/libs/demo-0.0.1-SNAPSHOT.jar']
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - backend

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: mydatabase
            MYSQL_USER: myuser
            MYSQL_PASSWORD: mypassword
        ports:
            - '3306:3306'
        volumes:
            - mysql_data_dev:/var/lib/mysql
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - backend

volumes:
    mysql_data_dev:

networks:
    backend:
        driver: bridge
