version: '3.8'

services:
    app:
        build: .
        image: sunbeen/saekdam-be:latest # Docker Hub에 푸시할 이미지 이름
        container_name: app-app
        ports:
            - '8080:8080'
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - backend

    mysql:
        image: mysql:8.0
        container_name: app-mysql
        ports:
            - '3306:3306'
        volumes:
            - mysql_data:/var/lib/mysql
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - backend

volumes:
    mysql_data:

networks:
    backend:
        driver: bridge
