spring:
    application:
        name: demo

    # 데이터베이스 연결 설정
    datasource:
        url: jdbc:mysql://mysql:3306/mydatabase
        username: myuser
        password: mypassword
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource

        # HikariCP 설정
        hikari:
            maximum-pool-size: 10
            minimum-idle: 5
            idle-timeout: 300000
            connection-timeout: 20000
            max-lifetime: 1200000
            auto-commit: true

    # JPA 설정
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MySQLDialect
        database-platform: org.hibernate.dialect.MySQLDialect

# 로깅 설정
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
                _root_: INFO
        com:
            zaxxer:
                hikari: DEBUG

# JWT 설정
jwt:
    secret: eW91ci12ZXJ5LWxvbmctYW5kLXNlY3VyZS1zZWNyZXQta2V5LWhlcmU=
    expiration: 86400000
